### ISSUE TITLE
install script fails

### ISSUE THREAD

**Issue by PingLord** [google/grr#92]
Hello guys,

I've tried to install the framework on a Ubuntu 12.04 server using the install script.The Ubuntu install is fresh.

The script failed at the following step :

FAILURE RUNNING: sudo grr_config_updater initialize

The python traceback :

Traceback (most recent call last):
  File "/usr/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.2', 'console_scripts', 'grr_config_updater')()
  File "/usr/lib/python2.7/dist-packages/grr/lib/distro_entry.py", line 46, in ConfigUpdater
    from grr.tools import config_updater
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 18, in <module>
    from grr.lib import server_plugins
  File "/usr/lib/python2.7/dist-packages/grr/lib/server_plugins.py", line 34, in <module>
    from grr.server import server_plugins
  File "/usr/lib/python2.7/dist-packages/grr/server/server_plugins.py", line 13, in <module>
    from grr.lib import export
  File "/usr/lib/python2.7/dist-packages/grr/lib/export.py", line 15, in <module>
    from google.protobuf import message_factory
ImportError: cannot import name message_factory

Have any ideas how it can be solved?
