### ISSUE TITLE
3.1.0rc2 server deb built with 2.7.6: "ImportError: No module named datetime"

### ISSUE THREAD

**Issue by destijl** [google/grr#365]
We built the rc2 server deb with python 2.7.6, which causes weirdness on systems with more modern python (Debian 8, Ubuntu 16.04).

On 2.7.6 datetime relies on a library which doesn't get added to the virtualenv:
```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.__file__
'/usr/lib/python2.7/lib-dynload/datetime.x86_64-linux-gnu.so'

ubuntu@ubuntu-xenial:/usr/share/grr-server$ find . -name "*.so" | grep datetime
ubuntu@ubuntu-xenial:/usr/share/grr-server$ 
```

So it tries to use the system one, but on 2.7.11 datetime is a builtin that doesn't require this file, so it doesn't work:
```
$ python2.7
Python 2.7.11+ (default, Apr 17 2016, 14:00:29)
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.__file__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__file__'
>>> 
```

and it looks like this:

```
$ /usr/share/grr-server/bin/grr_console
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_console", line 7, in <module>
    from grr.lib.distro_entry import Console
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 9, in <module>
    from grr.lib import config_lib
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/lib/config_lib.py", line 22, in <module>
    import pkg_resources
  File "/usr/share/grr-server/lib/python2.7/site-packages/pkg_resources/__init__.py", line 34, in <module>
    import plistlib
  File "/usr/lib/python2.7/plistlib.py", line 62, in <module>
    import datetime
ImportError: No module named datetime
```

Solution is to make sure we build with 2.7.11.
